"""Paper step 21: paper_results/PAPER_RESULTS_SUMMARY.md -- a factual summary for
the authors, not the paper.

    python scripts/paper/summary.py

Every number is read from a result file by this script. Comparisons are stated
as a difference with its 95% interval and whether the interval excludes zero;
no adjective is attached to any result. A section whose results do not exist yet
says so and names what is missing.
"""

from __future__ import annotations

import csv
import json

from pathlib import Path

from common import PAPER, ROOT, stamp, write_text  # noqa: E402  (sets sys.path)
from solarflare.settings import load_settings

S = load_settings()
HEADS = {"in_flare": "flare in progress", "flare_within_15min": "flare within 15 min",
         "flare_within_30min": "flare within 30 min", "flare_within_60min": "flare within 60 min"}


def _csv(name: str) -> list[dict] | None:
    p = PAPER / name
    if not p.exists():
        return None
    with open(p, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _json(name: str, base=PAPER) -> dict | None:
    p = base / name
    return json.loads(p.read_text("utf-8")) if p.exists() else None


def _one(rows, **kw):
    got = [r for r in rows or [] if all(str(r.get(k)) == str(v) for k, v in kw.items())]
    return got[0] if got else None


def v(r, nd=3) -> str:
    if not r:
        return "n/a"
    s = f"{float(r['value']):.{nd}f}"
    lo, hi = r.get("ci95_low"), r.get("ci95_high")
    return s + (f" [{float(lo):.{nd}f}, {float(hi):.{nd}f}]" if lo not in (None, "", "None") else "")


def missing(what: str) -> list[str]:
    return [f"Not yet available: {what}.", ""]


def main() -> int:
    inv, sp, ex = _json("01_data_inventory.json"), _json("02_experiment_split.json"), _json("experiments.json")
    man = _json("RESULTS_MANIFEST.json")
    cl, fx, un, pr = (_csv("metrics_classification.csv"), _csv("metrics_forecast.csv"),
                      _csv("metrics_uncertainty.csv"), _csv("paired_comparisons.csv"))
    lt, lsrc = _csv("leadtime_summary.csv"), _json("leadtime_source.json")
    L = ["# Paper 1 results summary (for the authors; not the manuscript)", "",
         f"Generated by scripts/paper/summary.py, {stamp()['generated_utc']} UTC, commit {stamp()['git_commit']}. "
         "Every number below is read from the files in paper_results/; comparisons give the difference, its 95% "
         "interval (whole test days resampled) and whether the interval excludes zero.", ""]

    L += ["## Status", ""]
    if man:
        for k, e in man["experiments"].items():
            run = Path(e["run"])
            L.append(f"- {k} (model.inputs = {e.get('inputs') or 'n/a'}): {e['status']} -- "
                     f"{run.relative_to(ROOT).as_posix() if run.is_relative_to(ROOT) else run}")
    L += ["- SUIT: excluded from Paper 1 (E3, E5, E6 not run).", ""]

    L += ["## Dataset", ""]
    if inv and sp:
        s, h, g = inv["SoLEXS"], inv["HEL1OS"], inv["GOES"]
        L += [f"- SoLEXS: {s['days_in_frozen_study']} days in the study ({s['observed_days_in_study']} observed days); "
              f"HEL1OS: {h['products_used_by_the_study']} products ({h['observed_days_in_study']} observed days); "
              f"{inv['cache_build']['failed']} unreadable products.",
              f"- GOES-18 XRS truth: {sum(g['flares_labelled_in_observed_segments_by_class'].values())} labelled flares "
              f">= {g['label_threshold']} inside observed data, by class "
              f"{g['flares_labelled_in_observed_segments_by_class']}.",
              "- Split (windows; GOES flares C/M/X peaking in the span):"]
        for k, x in sp["splits"].items():
            c = x["goes_flares_by_class"]
            L.append(f"  - {k}: {x['first_origin_utc'][:10]} to {x['last_origin_utc'][:10]}, {x['windows']:,} windows, "
                     f"in-flare rate {x['in_flare']['rate']}, flares {c.get('C', 0)}/{c.get('M', 0)}/{c.get('X', 0)}")
        L += [f"- Embargo {sp['checks']['embargo_days']:g} days; all split checks passed "
              f"({', '.join(k for k, val in sp['checks'].items() if val is True)}).", ""]
    else:
        L += missing("01_data_inventory.json / 02_experiment_split.json")

    L += ["## Experimental design", ""]
    if ex:
        for k, e in ex["experiments"].items():
            L.append(f"- {k}: {e['label']}, model.inputs = {e['inputs']}, seed {e['seed']}, best epoch "
                     f"{e['best_epoch']}, {e['parameters']:,} parameters.")
        c = ex["populations_test"]["common"]
        L += [f"- Common test windows (both instruments observing): {c['windows']:,} on {c['days']} days.",
              f"- Thresholds: {ex['thresholds']}. Calibration: {ex['calibration']}.",
              f"- Bootstrap: {ex['bootstrap']['method']}; {ex['bootstrap']['n_boot']} draws "
              f"({ex['bootstrap']['n_boot_auc']} for AUC), seed {ex['bootstrap']['seed']}.", ""]
    else:
        L += missing("experiments.json (scripts/paper/evaluate_experiments.py waits for E1 and E2)")

    L += ["## Main comparison: E4 against E1 and E2 (paired, common test windows)", ""]
    if pr:
        for comp in ("E4 - E1", "E4 - E2"):
            L.append(f"- {comp}:")
            for q, lab in HEADS.items():
                parts = [f"{m} {v(_one(pr, comparison=comp, quantity=q, metric=m))} "
                         f"(excludes 0: {(_one(pr, comparison=comp, quantity=q, metric=m) or {}).get('ci_excludes_zero')})"
                         for m in ("ROC_AUC", "TSS", "BSS_calibrated")]
                L.append(f"  - {lab}: " + "; ".join(parts))
            flux = [f"{'now' if r['horizon_min'] == '0' else '+' + r['horizon_min'] + ' min'} {v(r, 4)} "
                    f"(excludes 0: {r['ci_excludes_zero']})" for r in pr
                    if r["comparison"] == comp and r["quantity"] == "flux"]
            L.append("  - flux MAE difference (dex; negative favours E4): " + "; ".join(flux))
        L.append("")
    else:
        L += missing("paired_comparisons.csv (needs E1 and E2)")

    L += ["## Classification (>= C1; common test windows)", ""]
    if cl:
        for e in ("E1", "E2", "E4"):
            for q, lab in HEADS.items():
                r = {m: _one(cl, experiment=e, population="common", head=q, metric=m)
                     for m in ("ROC_AUC", "TSS", "frequency_bias", "BSS_calibrated")}
                if r["TSS"]:
                    L.append(f"- {e}, {lab}: AUC {v(r['ROC_AUC'])}, TSS {v(r['TSS'])}, FB "
                             f"{float(r['frequency_bias']['value']):.2f}, calibrated BSS {v(r['BSS_calibrated'])} "
                             f"({r['TSS']['n_samples']} windows, {r['TSS']['n_positive']} positive).")
        L.append("")
    else:
        L += missing("metrics_classification.csv")

    L += ["## Flux forecasting (common test windows, MAE of log10 flux, dex)", ""]
    if fx:
        hs = sorted({int(r["horizon_min"]) for r in fx if r["population"] == "common"})
        for e in ("E1", "E2", "E4", "reference: GOES flux now (persistence)", "reference: SoLEXS flux now (calibrated on training)",
                  "reference: climatology (training mean)"):
            vals = [f"{'now' if h == 0 else '+' + str(h)}: {v(_one(fx, experiment=e, population='common', horizon_min=h, metric='MAE'))}"
                    for h in hs if _one(fx, experiment=e, population="common", horizon_min=h, metric="MAE")]
            if vals:
                L.append(f"- {e}: " + "; ".join(vals))
        L.append("")
    else:
        L += missing("metrics_forecast.csv")

    L += ["## Calibration (each experiment's own test windows)", ""]
    if cl:
        for e in ("E1", "E2", "E4"):
            for q, lab in HEADS.items():
                a = _one(cl, experiment=e, population="native", head=q, metric="BSS_raw")
                b = _one(cl, experiment=e, population="native", head=q, metric="BSS_calibrated")
                if a:
                    L.append(f"- {e}, {lab}: BSS raw {float(a['value']):.3f} -> calibrated {v(b)}")
        L.append("")
    else:
        L += missing("metrics_classification.csv")

    L += ["## Prediction intervals (q10-q90; each experiment's own test windows)", ""]
    if un:
        for e in ("E1", "E2", "E4"):
            parts = []
            for h in sorted({int(r["horizon_min"]) for r in un if r["experiment"] == e}):
                c1 = _one(un, experiment=e, population="native", horizon_min=h, metric="coverage_raw")
                c2 = _one(un, experiment=e, population="native", horizon_min=h, metric="coverage_scaled")
                if c1:
                    parts.append(f"+{h} min {float(c1['value']):.3f} -> {float(c2['value']):.3f}")
            if parts:
                L.append(f"- {e} coverage raw -> validation-scaled (nominal 0.8): " + "; ".join(parts))
        L.append("")
    else:
        L += missing("metrics_uncertainty.csv")

    L += ["## Lead time and false alarms (E4 alerts; thresholds fixed on validation)", ""]
    if lt and lsrc:
        prim = lsrc["primary_false_alarms_per_day"]
        for r in lt:
            c = "C" if r["alert"].startswith("GOES >= C1") else "M"
            if r["scope"] == "all flares" and r["operating_point"] == f"fa_{prim[c]:g}":
                L.append(f"- {r['alert']}, {r['method']}: detected {r['detection_rate']} of {r['n_flares']} flares "
                         f"(chance {r['chance_rate']}), {r['false_alarms_per_day_test']} false alarms/day on test, time "
                         f"on {r.get('alert_on_fraction_test')}, median lead {r['median_lead_min']} min "
                         f"(IQR {r['q25_lead_min']}-{r['q75_lead_min']}).")
        small = [r for r in lt if r.get("note")]
        if small:
            L.append(f"- Class statistics flagged for too few flares: "
                     f"{sorted({r['scope'] + ' (n=' + r['n_flares'] + ')' for r in small})}.")
        L.append("")
    else:
        L += missing("leadtime_summary.csv")

    L += ["## Robustness (E4 with an instrument withheld; common test windows)", ""]
    if cl:
        for e in ("E4", "E4, HEL1OS withheld", "E1", "E4, SoLEXS withheld", "E2"):
            r = _one(cl, experiment=e, population="common", head="in_flare", metric="ROC_AUC")
            t = _one(cl, experiment=e, population="common", head="in_flare", metric="TSS")
            if r:
                L.append(f"- {e}: AUC (in progress) {v(r)}, TSS {v(t)}")
        L.append("")
    else:
        L += missing("metrics_classification.csv")

    L += ["## Robustness to real observation gaps (each experiment's own test windows)", ""]
    gr = _csv("metrics_gap_robustness.csv")
    if gr:
        L.append("Windows grouped by the fraction of the 2 h input the instrument observed (E1 / E2: at least 50% "
                 "by the window rule; E4 below 50% where the other instrument carried the window); in-progress AUC "
                 "and TSS, flux MAE at +15 min:")
        for key in dict.fromkeys((r["experiment"], r["instrument"], r["coverage_group"]) for r in gr):
            sel = [r for r in gr if (r["experiment"], r["instrument"], r["coverage_group"]) == key]
            a = _one(sel, head="in_flare", metric="ROC_AUC")
            t = _one(sel, head="in_flare", metric="TSS")
            m = _one(sel, horizon_min=15, metric="MAE")
            few = "; fewer than 30 flare windows, indicative only" if a and int(a["n_positive"]) < 30 else ""
            L.append(f"- {key[0]}, {key[1]} coverage {key[2]} ({a['n_samples'] if a else '?'} windows, "
                     f"{a['n_positive'] if a else '?'} flare windows{few}): AUC {v(a)}, TSS {v(t)}, MAE +15 min {v(m)}")
        L.append("")
    else:
        L += missing("metrics_gap_robustness.csv (scripts/paper/gap_robustness.py)")

    L += ["## Ablation (existing, separately trained, 3 seeds)", ""]
    hv = _json("hel1os_value.json", S.ablations / "hel1os")
    if hv:
        L += ["- Soft-only vs soft + hard rise-phase models, peak log-MAE reduction with HEL1OS: "
              + "; ".join(f"seed {s['seed'].removeprefix('seed_')} {s['gain_dex']:.4f} [{s['ci'][0]:.4f}, {s['ci'][1]:.4f}] "
                          f"dex ({s['n_flares']} flares)" for s in hv["seeds"]) + f"; {hv['verdict']}.", ""]

    L += ["## Limitations supported by the results", ""]
    lim = []
    if sp:
        te, tr = sp["splits"]["test"], sp["splits"]["train"]
        lim.append(f"One chronological test block ({te['first_origin_utc'][:10]} to {te['last_origin_utc'][:10]}) "
                   f"with {te['goes_flares_by_class']} flares; no other part of the solar cycle is tested.")
        lim.append(f"Base rate shift: in-flare rate {tr['in_flare']['rate']} (training) vs {te['in_flare']['rate']} "
                   "(test); validation thresholds are conservative on test (outputs/tests/forecast_bias).")
    if man:
        lim.append("One training seed per experiment for the main network (seeds: "
                   f"{man['seeds']['training']}); training variation is not in the intervals, which resample test days "
                   "only. Seed variation is measured only for the rise-phase ablation (3 seeds).")
    lim += ["Only the >= C1 threshold is a model head; M1 is evaluated through alerts; X-class counts are too small "
            "for statistics.",
            "Flare onsets are GOES start times; an Aditya-only system would detect onsets itself.",
            "Design choices were made while earlier runs' test scores were visible (02b_leakage_prevention.md, "
            "section 6); only sealed forecasts after the study are free of this."]
    pk = _json("peak_nowcast.json", S.tests / "peak_nowcast")
    if pk and pk["final_test_period"].get("C_vs_M_validation_cut_paired"):
        d = pk["final_test_period"]["C_vs_M_validation_cut_paired"]
        lim.append(f"Calling C vs >= M 3 min after onset, the network's TSS minus the GOES-now rule's is "
                   f"{d['TSS_diff']} {d['ci95']} (outputs/tests/peak_nowcast).")
    L += [f"- {x}" for x in lim] + [""]
    write_text("PAPER_RESULTS_SUMMARY.md", "\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
